server:
  port: 8080
  url: "https://dummyjson.com/"
spring:
    cloud:
        openfeign:
            client:
                config:
                    default:
                        connectTimeout: 5000
                        readTimeout: 5000
                        loggerLevel: basic
management:
  endpoint:
    health:
      show-details: always